@url = http://localhost:8000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTJmNDJiMzAxMDgxOTA4ZTA5ZDgxM2IiLCJpYXQiOjE2MzA4NTE4OTgsImV4cCI6MTYzMDkzODI5OH0.6ccN3yP9hvn5kFeTYIazjtYPFEbupwtFXSlPC5PSj1w

## User Registration ##
POST {{url}}/signup
Content-Type: application/json

{
    "firstName" : "angelo3",
    "lastName" : "santiago3",
    "email" : "angelo.santiago3@gmails.com",
    "mobileNumber" : "090788388331",
    "referralNumber" : "",
    "password" : "12345678"
 

}

### User Signin ###
POST {{url}}/signin
Content-Type: application/json

{
   "mobileNumber" : "090788388331",
   "password" : "12345678"
}

### Get Wallet ###
POST {{url}}/user/getgameslink/ppgames
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userId" : 718843360,
   "gameCode" : "vs5drhs"
}

### Get Wallet ###
POST {{url}}/user/reloadPPwallet/ppgames
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userId" : 718843360,
   "amountP" : 100,
   "transaction" : "OUT"
}



### Get Wallet ###
GET {{url}}/user/getbalance/ppgames/718843360
Authorization: Bearer {{token}}


### get wallet balance##
GET {{url}}/user/getWallet/718843360
Authorization: Bearer {{token}}


### get wallet balance##
GET {{url}}/user/request/balance/718843360
Authorization: Bearer {{token}}

### Add wallet request ##
POST {{url}}/user/addWallet
Authorization: Bearer {{token}}
Content-Type: application/json

{
"playerID" : 718843360, 
"amount" : 1000,
"transType" : "Deposit"
}

###

PUT {{url}}/user/updateUserWalletRequest/Uwr1630852274927
Authorization: Bearer {{token}}
Content-Type: application/json

{
"status" : "Cancel"
}




### USER PROFILE ###
GET {{url}}/user/profile/718843360
Authorization: Bearer {{token}}


### USER PROFILE ###
PUT {{url}}/user/update/profile/718843360
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "userId": "718843360",
  "firstName": "Leona",
  "lastName": "lewis",
  "mobileNumber": "324234234263",
  "email": "leona.lewis6@gmails.com"
}
