@url = http://localhost:8000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTIyM2JmMDI1OTIwMzFiZDhkNGJjMjkiLCJpYXQiOjE2MzMxNzk3OTksImV4cCI6MTYzMzI2NjE5OX0.NnLJUQdYtyU0By1PbvCKD0sBbwHqRSx1S9wDiNE4tPI

## User Registration ##
POST {{url}}/admin/signup
Content-Type: application/json

{   
    "username" : "admin",
    "firstName" : "admin",
    "lastName" : "admin",
    "email" : "admin@euGaming.com",
    "MobileNumber" : "765765234",
    "password" : "12345678",
    "address" : "adssadas"
 
}

###
POST {{url}}/admin/signin
Content-Type: application/json

{
   "username" : "admin",
   "password" : "123456"
}

### get all user ###
GET {{url}}/admin/getAllUser
Authorization: Bearer {{token}}

### get one user ###
GET {{url}}/admin/getUser/638699556
Authorization: Bearer {{token}}

### update user status ###
PUT {{url}}/admin/updateUser/638699556
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "active" : true
}

### Add User Wallet ###
POST {{url}}/admin/wallet
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "OwnerID" : "5ff4107d20076717446a0c58", 
    "Balance" : 2000, 
    "Owner" : "dan.est@gmail.com"

}


### Add User Wallet ###
POST {{url}}/admin/add-games
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "englishGameName" : "Force 1", 
    "chineseGameName" : "方程式赛车1", 
    "gameSymbolApi" : "VPmr9",
    "gameCategory" : "Video Slots",
    "gameAvatar" : ""

}
###

PUT {{url}}/admin/update-game-id/vswaysbufking
Content-Type: application/json
Authorization: Bearer {{token}}

{  
    "gameAvatar" : "https://drive.google.com/file/d/1YYSDPP_DxA3DLf3GOtQpyEqcMbfrWSZh/view?usp=sharing"
}

### get all user wallets ###
GET {{url}}/admin/get-all-games?catergory=Video Slots&pagination=12&page=1
Authorization: Bearer {{token}}

### get all user wallets ###
GET {{url}}/admin/getOneGame/vs25wolfgold
Authorization: Bearer {{token}}
### get one user wallets ###
GET {{url}}/admin/wallet/getOne/613f064dd6a2c824303b7036
Authorization: Bearer {{token}}


### update one user wallet ###
PUT {{url}}/admin/wallet/updateOne/5ff4107d20076717446a0c58
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "OwnerID" : "5ff40d023311b43234f62031",
    "Owner" : "sam.ekwe@gmail.com"
}

### get 1 user wallet ####
GET {{url}}/admin/wallet/getOne/user/5ff4107d20076717446a0c58
Authorization: Bearer {{token}}


### get 1 user wallet ####
PUT {{url}}/admin/requested/wallet/update/Uwr1630487665963
Authorization: Bearer {{token}}
Content-Type: application/json

{
"status" : "Granted!"

}

### get 1 user wallet ####
GET {{url}}/admin/walletRequest/getAll/user?status=pending&pagination=10&page=1
Authorization: Bearer {{token}}

### get 1 user wallet ####
GET {{url}}/admin/walletRequest/getOne/user/Uwr1630484325343
Authorization: Bearer {{token}}


### get 1 user wallet ####
GET {{url}}/admin/getWallets?status=false&pagination=10&page=1
Authorization: Bearer {{token}}
