@url = http://localhost:8000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmY0MjI4ZDIwMDc2NzE3NDQ2YTBjNTkiLCJpYXQiOjE2MTA5NTI3OTYsImV4cCI6MTYxMTAzOTE5Nn0.iM3q03VhfnIR8ahM8KWeDnJvxuP3dkSeILrP3UGEeos

## User Registration ##
POST {{url}}/admin/signup
Content-Type: application/json

{   
    "username" : "admin",
    "firstName" : "admin",
    "lastName" : "admin",
    "email" : "admin@euGaming.com",
    "MobileNumber" : "765765234",
    "password" : "12345678",
    "address" : "adssadas"
 
}

###
POST {{url}}/admin/signin
Content-Type: application/json

{
   "username" : "admin",
   "password" : "1234567"
}

### get all user ###
GET {{url}}/admin/getAllUser
Authorization: Bearer {{token}}

### get one user ###
GET {{url}}/admin/getUser/5ff40d023311b43234f62031
Authorization: Bearer {{token}}

### update user status ###
PUT {{url}}/admin/updateUser/5ff40d023311b43234f62031
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "active" : true
}

### Add User Wallet ###
POST {{url}}/admin/wallet
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "OwnerID" : "5ff4107d20076717446a0c58", 
    "Balance" : 2000, 
    "Owner" : "dan.est@gmail.com"

}

### get all user wallets ###
GET {{url}}/admin/getWallets
Authorization: Bearer {{token}}

### get one user wallets ###
GET {{url}}/admin/wallet/getOne/60052f7eb813601ee8a66a62
Authorization: Bearer {{token}}


### update one user wallet ###
PUT {{url}}/admin/wallet/updateOne/5ff4107d20076717446a0c58
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "OwnerID" : "5ff40d023311b43234f62031",
    "Owner" : "sam.ekwe@gmail.com"
}

### get 1 user wallet ####
GET {{url}}/admin/wallet/getOne/user/5ff4107d20076717446a0c58
Authorization: Bearer {{token}}