@url = http://localhost:8000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTIyNTAyYjMyYjcyOTI4ZDBkY2EzZmYiLCJpYXQiOjE2Mjk2NDM0MTcsImV4cCI6MTYyOTcyOTgxN30.E-FuQ3mHyqn6_HQ5rZWhgNbJfyj0F_oYYPIRokE83n4

## User Registration ##
POST {{url}}/signup
Content-Type: application/json

{
    "firstName" : "Leona",
    "lastName" : "lewis",
    "email" : "Leona.lewis@gmails.com",
    "mobileNumber" : "765765234",
    "referralNumber" : "",
    "password" : "12345678"
 

}

### User Signin ###
POST {{url}}/signin
Content-Type: application/json

{
   "mobileNumber" : "765765234",
   "password" : "12345678"
}

### Get Wallet ###
POST {{url}}/user/getgameslink/ppgames
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userId" : 638699556,
   "gameCode" : "vs25hotfiesta"
}




### Get Wallet ###
GET {{url}}/user/getbalance/ppgames/638699556
Authorization: Bearer {{token}}



### Add wallet ##
POST {{url}}/user/getWallet/:slug
Content-Type: application/json

{
   "MobileNumber" : "09881234455",
   "password" : "12345678"
}

### Get Wallet ###
GET {{url}}/user/getWallet/5ff4107d20076717446a0c58
Authorization: Bearer {{token}}

### Request wallet load ###
POST 

### USER PROFILE ###
GET {{url}}/user/profile/5ff4107d20076717446a0c58
Authorization: Bearer {{token}}