@url = http://localhost:8000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTJmNDJiMzAxMDgxOTA4ZTA5ZDgxM2IiLCJpYXQiOjE2MzM2MDQ0NzgsImV4cCI6MTYzMzY5MDg3OH0.H7ft24l1xoLtcxKqQT95om6uYeFQQV0xYXACFFGJXQ8

## User Registration ##
POST {{url}}/signup
Content-Type: application/json

{
    "firstName" : "angelo4",
    "lastName" : "santiago4",
    "email" : "angelo.santiagoss5@gmails.com",
    "mobileNumber" : "090788388221",
    "referralNumber" : "",
    "password" : "12345678",
    "userName" : "angelo1234"
 

}

### User Signin ###
POST {{url}}/signin
Content-Type: application/json

{
   "userName" : "demoCS30",
   "password" : "12345678"
}

### Get Wallet ###
POST {{url}}/user/getgameslink/ppgames
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userId" : 718843360,
   "gameCode" : "vs5drhs"
}

### Get Wallet ###
POST {{url}}/user/reloadPPwallet/ppgames
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userId" : 718843360,
   "amountP" : 100,
   "transaction" : "OUT"
}



### Get Wallet ###
GET {{url}}/user/getbalance/ppgames/718843360
Authorization: Bearer {{token}}


### get wallet balance##
GET {{url}}/user/getWallet/718843360
Authorization: Bearer {{token}}


### get wallet balance##
GET {{url}}/user/request/balance/718843360
Authorization: Bearer {{token}}

### Add wallet request ##
POST {{url}}/user/addWallet
Authorization: Bearer {{token}}
Content-Type: application/json

{
"playerID" : 718843360, 
"amount" : 1000,
"transType" : "Deposit"
}

###

PUT {{url}}/user/updateUserWalletRequest/Uwr1630852274927
Authorization: Bearer {{token}}
Content-Type: application/json

{
"status" : "Cancel"
}




### USER PROFILE ###
GET {{url}}/user/profile/718843360
Authorization: Bearer {{token}}


### USER PROFILE ###
PUT {{url}}/user/update/profile/718843360
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "userName": "demoCS30"
}


###
GET {{url}}/user/get-all-games?catergory=Video Slots&pagination=12&page=1
Authorization: Bearer {{token}}

### get all user wallets ###
GET {{url}}/user/get-one-game/vs25wolfgold
Authorization: Bearer {{token}}